# Site
repository:  tipapro/tipapro.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Богомолов Андрей
title: Android Developer
email: tipapro@hotmail.com
#website: www.github.com/tipapro

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  tipapro
linkedin_username: tipapro

# Additional icon links
additional_links:
- title: telegram
  icon: fab fa-telegram
  url: https://telegram.me/anbotip
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
about_title: Обо мне
#about_profile_image: images/profile.jpg
about_content: |
  С лета 2016 года программирую на C#. За это время написал разные проекты на нём (WPF, .Net Core бот для Discord, Asp Net Core Web Api + Vue.js + TS)
  С 06.2019 пишу под Android. 06.2019 - 03.2020 – на Xamarin.Android (C#). С 04.2020 – на kotlin.
  Люблю развивать, улучшать и экспериментировать с архитектурой проекта в поисках более простого и удобного варианта.

content:
  - title: Скиллы
    layout: list
    content:
      - layout: left
        title: kotlin
        caption: |
          - UI: Jetpack Compose, Material (2), Material You (3), View Binding
          - Изображения: Coil, Glide
          - Сеть: Retrofit, OkHttp, Ktor, Paging 3
          - Навигация: Cicerone, Jetpack Navigation
          - DI: Koin, Kodein, Dagger 2 (редко использовал)
          - Сериализация: kotlinx.serialization, GSON
          - Потоки данных: Flow + Coroutines, RxJava 3 (редко использовал)
          - Хранение данных: Room, KodeinDB, файловая система Android
          - Прочее: CameraX, Jsoup, Glance Appwidget
      - layout: left
        title: Архитектуры
        caption: |
          MVVM, MVI, UDF, Clean
      - layout: right
        title: Инструментарий
        caption: |
          Github, Jira, Trello, Figma


  - title: Проекты
    layout: list
    content:
      - layout: left
        title: Edugma
        link: github.com/Edugma/app
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: github.com/Edugma/app
        description: |
          Децентрализованное мобильное приложение для учебных заведений. К нему может подключиться любое учебное заведение, подняв свой узел и реализовав нужный API. Пока в процессе (мои schedule фичи). Также пишу узел (Web API) для Московского политеха (kotlin + ktor)
      
      - layout: left
        title: mospolyhelper
        link: github.com/mospolyhelper/mospolyhelper-android
        # link_text: Project Website
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: github.com/mospolyhelper/mospolyhelper-android
          - title:  Google Play
            icon: fab fa-google-play
            url: play.google.com/store/apps/details?id=com.mospolytech.mospolyhelper
        description: |
          Мобильное приложение для Московского Политеха. <mark>3000 загрузок</mark> (Android приложение + Asp Net Core Web Api + вебсайт на Vue.js)

  - title: Опыт работы
    layout: list
    content:
      - layout: left
        title: Дар (Российский офис)
        link: dar.io
        sub_title: Android Developer
        caption: Май 2020 — Апрель 2022 (2 года)
        description: |
            Кодил в разных проектах:
            - писал фичи в приложении для инвестирования (для России и для Великобритании),
            - проектировал архитектуру и писал с нуля приложение для частого поcёлка и приложение для оплаты чавеых по лицу/QR коду
            - переносил дизайн-систему (палитру (светлую и тёмную) + элементы) из фигмы
            - рефакторил архитектуру приложения

  - title: Образование
    layout: list
    content:
      - layout: left
        title: Московский политехнический университет
        caption: 2018 - 2022
        sub_title: Бакалавриат "Информационные системы и технологии"
        description: |
          За время обучения успел попробовать множество направлений и языков, прежде чем нашёл себя в мобильной разработке. Успел поработать в разных командах (от 2 до 5 человек)
          
          Разрабатывал
          - бота для Discord на C#
          - игру на Unity (С#)
          - Desktop приложение на WPF (C#)
          - мобильное приложение на Xamarin.Android (C#), впоследствии на kotlin
          - веб API на ASP NET Core (C#), впоследствии на ktor (kotlin)
          - веб сайт на Vue (TS)
          - бэкенд для работы с нейросетью на Python


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
